"""add thumb url for posts

Revision ID: 65138699781f
Revises: 5afb9e05a40d
Create Date: 2019-05-25 20:55:53.747945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65138699781f'
down_revision = '5afb9e05a40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumb_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumb_url')
    # ### end Alembic commands ###
